// <auto-generated />
namespace Web_Datamining.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class caigido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(caigido));
        
        string IMigrationMetadata.Id
        {
            get { return "201810210822259_caigido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
